#
#  ██╗  ██╗ ██████╗
#  ██║  ██║██╔═══██╗   Håkon Otneim
#  ███████║██║   ██║   haakon.otneim@protonmail.com
#  ██╔══██║██║   ██║   hotneim.github.com
#  ██║  ██║╚██████╔
#  ╚═╝  ╚═╝ ╚═════╝
#
# configuration for the alacritty terminal emulator

import = ["~/.config/alacritty/themes/github_dark_default.toml"]

[font]
size = 16

[font.normal]
# family = "Comic Code Ligatures"
family = "FiraCode Nerd Font Mono"
style = "Light"

# [font.italic]
# family = "Comic Code Ligatures"
# style = "Light Italic"
#
[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Medium"

# [font.bold_italic]
# family = "Comic Code Ligatures"
# style = "Medium Italic"
#
[window]
dimensions = { columns = 100, lines = 70}

[keyboard]
bindings = [
  { key = "Return", mods = "Control", chars = "\\x0d" }
]

[env]
term = "xterm-256color"
