format = "$conda$directory$character"
right_format = '$git_branch$git_commit$git_state$git_metrics$git_status'
# Inserts a blank line between shell prompts
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
format = '[$symbol$environment](red dimmed) '
symbol = '󰌠 '
ignore_base = true
